apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    type: cm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cmcc
    server: https://kubernetes.default.svc
  project: cmcc
  sources:
    - repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      ref: common

    - path: coremedia/cae-live
      repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      helm:
        releaseName: app-1
        valueFiles:
          - $common/cm-app-versions/global.yaml
          - repl-1.yaml
          - $common/cm-app-versions/{{ .Values.env }}-versions.yaml

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    type: cm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cmcc
    server: https://kubernetes.default.svc
  project: cmcc
  sources:
    - repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      ref: common

    - path: coremedia/cae-live
      repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      helm:
        releaseName: app-2
        valueFiles:
          - $common/cm-app-versions/global.yaml
          - repl-2.yaml
          - $common/cm-app-versions/{{ .Values.env }}-versions.yaml
