apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: content-management-server
  namespace: cmcc
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cmcc
    server: https://kubernetes.default.svc
  project: cmcc
  sources:
  - repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    ref: common
  - path: coremedia/content-management-server
    repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - $common/cm-app-versions/global.yaml
        - $common/cm-app-versions/{{ .Values.env }}-versions.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: studio-server
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      ref: common
    - path: coremedia/studio-server
      repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      helm:
        valueFiles:
          - $common/cm-app-versions/global.yaml
          - $common/cm-app-versions/{{ .Values.env }}-versions.yaml

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cae-live-1
  namespace: default
  labels:
    type: cm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cmcc
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      ref: common

    - path: coremedia/cae-live
      repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      helm:
        releaseName: cae-live-1
        valueFiles:
          - $common/cm-app-versions/global.yaml
          - repl-1.yaml
          - $common/cm-app-versions/{{ .Values.env }}-versions.yaml

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cae-live-2
  namespace: default
  labels:
    type: cm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cmcc
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      ref: common

    - path: coremedia/cae-live
      repoURL: https://github.com/matlion/argocd-example-apps.git
      targetRevision: HEAD
      helm:
        releaseName: cae-live-2
        valueFiles:
          - $common/cm-app-versions/global.yaml
          - repl-2.yaml
          - $common/cm-app-versions/{{ .Values.env }}-versions.yaml
