apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      initContainers:
        - name: wait-for-content-management-server
          image: busybox:1.28.2
          command: ['sh', '-c', 'sleep 30']
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
