apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cm-demo
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cmcc
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    ref: common
  - path: coremedia/content-management-server
    repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - $common/coremedia/common/global.yaml
  - path: coremedia/studio-server
    repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - $common/coremedia/common/global.yaml
  - path: coremedia/cae-preview
    repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - $common/coremedia/common/global.yaml
  - path: coremedia/cae-live
    repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      releaseName: cae-live-1
      valueFiles:
        - $common/coremedia/common/global.yaml
        - repl-1.yaml
  - path: coremedia/cae-live
    repoURL: https://github.com/matlion/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      releaseName: cae-live-2
      valueFiles:
        - repl-2.yaml
        - $common/coremedia/common/global.yaml
