apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golist
  namespace: default
spec:
  source:
    path: appshelm
    repoURL: 'https://github.com/matlion/argocd-example-apps.git'
    targetRevision: main
  destination:
    namespace: prod
    server: 'https://kubernetes.default.svc'
  project: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
