apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coremedia
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: cm-app
    repoURL: 'https://github.com/matlion/argocd-example-apps.git'
    targetRevision: master
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
